/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MarketingRouteRouteImport } from './routes/_marketing/route'
import { Route as MarketingIndexRouteImport } from './routes/_marketing/index'
import { Route as MarketingTermsOfServiceRouteImport } from './routes/_marketing/terms-of-service'
import { Route as MarketingPrivacyPolicyRouteImport } from './routes/_marketing/privacy-policy'
import { Route as errors503RouteImport } from './routes/(errors)/503'
import { Route as errors500RouteImport } from './routes/(errors)/500'
import { Route as errors404RouteImport } from './routes/(errors)/404'
import { Route as errors403RouteImport } from './routes/(errors)/403'
import { Route as errors401RouteImport } from './routes/(errors)/401'
import { Route as MarketingAiAgentsIndexRouteImport } from './routes/_marketing/ai-agents/index'
import { Route as MarketingSolutionsValueBasedCareRouteImport } from './routes/_marketing/solutions/value-based-care'
import { Route as MarketingSolutionsPrivateEquityRouteImport } from './routes/_marketing/solutions/private-equity'
import { Route as MarketingSolutionsEmrIntegrationRouteImport } from './routes/_marketing/solutions/emr-integration'
import { Route as MarketingSolutionsDermatologyRouteImport } from './routes/_marketing/solutions/dermatology'
import { Route as MarketingSolutionsBehavioralHealthRouteImport } from './routes/_marketing/solutions/behavioral-health'
import { Route as MarketingAiAgentsSmsRouteImport } from './routes/_marketing/ai-agents/sms'
import { Route as MarketingAiAgentsScribeRouteImport } from './routes/_marketing/ai-agents/scribe'
import { Route as MarketingAiAgentsRevenueCycleRouteImport } from './routes/_marketing/ai-agents/revenue-cycle'
import { Route as MarketingAiAgentsReferralManagementRouteImport } from './routes/_marketing/ai-agents/referral-management'
import { Route as MarketingAiAgentsPriorAuthorizationRouteImport } from './routes/_marketing/ai-agents/prior-authorization'
import { Route as MarketingAiAgentsPhoneRouteImport } from './routes/_marketing/ai-agents/phone'
import { Route as MarketingAiAgentsPaymentPostingRouteImport } from './routes/_marketing/ai-agents/payment-posting'
import { Route as MarketingAiAgentsPatientIntakeRouteImport } from './routes/_marketing/ai-agents/patient-intake'
import { Route as MarketingAiAgentsPatientExperienceRouteImport } from './routes/_marketing/ai-agents/patient-experience'
import { Route as MarketingAiAgentsPatientEducationRouteImport } from './routes/_marketing/ai-agents/patient-education'
import { Route as MarketingAiAgentsFaxRouteImport } from './routes/_marketing/ai-agents/fax'
import { Route as MarketingAiAgentsEmailRouteImport } from './routes/_marketing/ai-agents/email'
import { Route as MarketingAiAgentsDenialManagementRouteImport } from './routes/_marketing/ai-agents/denial-management'
import { Route as MarketingAiAgentsCommunicationRouteImport } from './routes/_marketing/ai-agents/communication'
import { Route as MarketingAiAgentsCodingBillingRouteImport } from './routes/_marketing/ai-agents/coding-billing'
import { Route as MarketingAiAgentsClinicalDocumentationRouteImport } from './routes/_marketing/ai-agents/clinical-documentation'
import { Route as MarketingAiAgentsClinicalRouteImport } from './routes/_marketing/ai-agents/clinical'
import { Route as MarketingAiAgentsChronicCareRouteImport } from './routes/_marketing/ai-agents/chronic-care'
import { Route as MarketingAiAgentsCareGapRouteImport } from './routes/_marketing/ai-agents/care-gap'
import { Route as MarketingAiAgentsCareCoordinationRouteImport } from './routes/_marketing/ai-agents/care-coordination'
import { Route as MarketingAiAgentsAppointmentCoordinationRouteImport } from './routes/_marketing/ai-agents/appointment-coordination'

const MarketingRouteRoute = MarketingRouteRouteImport.update({
  id: '/_marketing',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketingIndexRoute = MarketingIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MarketingRouteRoute,
} as any)
const MarketingTermsOfServiceRoute = MarketingTermsOfServiceRouteImport.update({
  id: '/terms-of-service',
  path: '/terms-of-service',
  getParentRoute: () => MarketingRouteRoute,
} as any)
const MarketingPrivacyPolicyRoute = MarketingPrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => MarketingRouteRoute,
} as any)
const errors503Route = errors503RouteImport.update({
  id: '/(errors)/503',
  path: '/503',
  getParentRoute: () => rootRouteImport,
} as any)
const errors500Route = errors500RouteImport.update({
  id: '/(errors)/500',
  path: '/500',
  getParentRoute: () => rootRouteImport,
} as any)
const errors404Route = errors404RouteImport.update({
  id: '/(errors)/404',
  path: '/404',
  getParentRoute: () => rootRouteImport,
} as any)
const errors403Route = errors403RouteImport.update({
  id: '/(errors)/403',
  path: '/403',
  getParentRoute: () => rootRouteImport,
} as any)
const errors401Route = errors401RouteImport.update({
  id: '/(errors)/401',
  path: '/401',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketingAiAgentsIndexRoute = MarketingAiAgentsIndexRouteImport.update({
  id: '/ai-agents/',
  path: '/ai-agents/',
  getParentRoute: () => MarketingRouteRoute,
} as any)
const MarketingSolutionsValueBasedCareRoute =
  MarketingSolutionsValueBasedCareRouteImport.update({
    id: '/solutions/value-based-care',
    path: '/solutions/value-based-care',
    getParentRoute: () => MarketingRouteRoute,
  } as any)
const MarketingSolutionsPrivateEquityRoute =
  MarketingSolutionsPrivateEquityRouteImport.update({
    id: '/solutions/private-equity',
    path: '/solutions/private-equity',
    getParentRoute: () => MarketingRouteRoute,
  } as any)
const MarketingSolutionsEmrIntegrationRoute =
  MarketingSolutionsEmrIntegrationRouteImport.update({
    id: '/solutions/emr-integration',
    path: '/solutions/emr-integration',
    getParentRoute: () => MarketingRouteRoute,
  } as any)
const MarketingSolutionsDermatologyRoute =
  MarketingSolutionsDermatologyRouteImport.update({
    id: '/solutions/dermatology',
    path: '/solutions/dermatology',
    getParentRoute: () => MarketingRouteRoute,
  } as any)
const MarketingSolutionsBehavioralHealthRoute =
  MarketingSolutionsBehavioralHealthRouteImport.update({
    id: '/solutions/behavioral-health',
    path: '/solutions/behavioral-health',
    getParentRoute: () => MarketingRouteRoute,
  } as any)
const MarketingAiAgentsSmsRoute = MarketingAiAgentsSmsRouteImport.update({
  id: '/ai-agents/sms',
  path: '/ai-agents/sms',
  getParentRoute: () => MarketingRouteRoute,
} as any)
const MarketingAiAgentsScribeRoute = MarketingAiAgentsScribeRouteImport.update({
  id: '/ai-agents/scribe',
  path: '/ai-agents/scribe',
  getParentRoute: () => MarketingRouteRoute,
} as any)
const MarketingAiAgentsRevenueCycleRoute =
  MarketingAiAgentsRevenueCycleRouteImport.update({
    id: '/ai-agents/revenue-cycle',
    path: '/ai-agents/revenue-cycle',
    getParentRoute: () => MarketingRouteRoute,
  } as any)
const MarketingAiAgentsReferralManagementRoute =
  MarketingAiAgentsReferralManagementRouteImport.update({
    id: '/ai-agents/referral-management',
    path: '/ai-agents/referral-management',
    getParentRoute: () => MarketingRouteRoute,
  } as any)
const MarketingAiAgentsPriorAuthorizationRoute =
  MarketingAiAgentsPriorAuthorizationRouteImport.update({
    id: '/ai-agents/prior-authorization',
    path: '/ai-agents/prior-authorization',
    getParentRoute: () => MarketingRouteRoute,
  } as any)
const MarketingAiAgentsPhoneRoute = MarketingAiAgentsPhoneRouteImport.update({
  id: '/ai-agents/phone',
  path: '/ai-agents/phone',
  getParentRoute: () => MarketingRouteRoute,
} as any)
const MarketingAiAgentsPaymentPostingRoute =
  MarketingAiAgentsPaymentPostingRouteImport.update({
    id: '/ai-agents/payment-posting',
    path: '/ai-agents/payment-posting',
    getParentRoute: () => MarketingRouteRoute,
  } as any)
const MarketingAiAgentsPatientIntakeRoute =
  MarketingAiAgentsPatientIntakeRouteImport.update({
    id: '/ai-agents/patient-intake',
    path: '/ai-agents/patient-intake',
    getParentRoute: () => MarketingRouteRoute,
  } as any)
const MarketingAiAgentsPatientExperienceRoute =
  MarketingAiAgentsPatientExperienceRouteImport.update({
    id: '/ai-agents/patient-experience',
    path: '/ai-agents/patient-experience',
    getParentRoute: () => MarketingRouteRoute,
  } as any)
const MarketingAiAgentsPatientEducationRoute =
  MarketingAiAgentsPatientEducationRouteImport.update({
    id: '/ai-agents/patient-education',
    path: '/ai-agents/patient-education',
    getParentRoute: () => MarketingRouteRoute,
  } as any)
const MarketingAiAgentsFaxRoute = MarketingAiAgentsFaxRouteImport.update({
  id: '/ai-agents/fax',
  path: '/ai-agents/fax',
  getParentRoute: () => MarketingRouteRoute,
} as any)
const MarketingAiAgentsEmailRoute = MarketingAiAgentsEmailRouteImport.update({
  id: '/ai-agents/email',
  path: '/ai-agents/email',
  getParentRoute: () => MarketingRouteRoute,
} as any)
const MarketingAiAgentsDenialManagementRoute =
  MarketingAiAgentsDenialManagementRouteImport.update({
    id: '/ai-agents/denial-management',
    path: '/ai-agents/denial-management',
    getParentRoute: () => MarketingRouteRoute,
  } as any)
const MarketingAiAgentsCommunicationRoute =
  MarketingAiAgentsCommunicationRouteImport.update({
    id: '/ai-agents/communication',
    path: '/ai-agents/communication',
    getParentRoute: () => MarketingRouteRoute,
  } as any)
const MarketingAiAgentsCodingBillingRoute =
  MarketingAiAgentsCodingBillingRouteImport.update({
    id: '/ai-agents/coding-billing',
    path: '/ai-agents/coding-billing',
    getParentRoute: () => MarketingRouteRoute,
  } as any)
const MarketingAiAgentsClinicalDocumentationRoute =
  MarketingAiAgentsClinicalDocumentationRouteImport.update({
    id: '/ai-agents/clinical-documentation',
    path: '/ai-agents/clinical-documentation',
    getParentRoute: () => MarketingRouteRoute,
  } as any)
const MarketingAiAgentsClinicalRoute =
  MarketingAiAgentsClinicalRouteImport.update({
    id: '/ai-agents/clinical',
    path: '/ai-agents/clinical',
    getParentRoute: () => MarketingRouteRoute,
  } as any)
const MarketingAiAgentsChronicCareRoute =
  MarketingAiAgentsChronicCareRouteImport.update({
    id: '/ai-agents/chronic-care',
    path: '/ai-agents/chronic-care',
    getParentRoute: () => MarketingRouteRoute,
  } as any)
const MarketingAiAgentsCareGapRoute =
  MarketingAiAgentsCareGapRouteImport.update({
    id: '/ai-agents/care-gap',
    path: '/ai-agents/care-gap',
    getParentRoute: () => MarketingRouteRoute,
  } as any)
const MarketingAiAgentsCareCoordinationRoute =
  MarketingAiAgentsCareCoordinationRouteImport.update({
    id: '/ai-agents/care-coordination',
    path: '/ai-agents/care-coordination',
    getParentRoute: () => MarketingRouteRoute,
  } as any)
const MarketingAiAgentsAppointmentCoordinationRoute =
  MarketingAiAgentsAppointmentCoordinationRouteImport.update({
    id: '/ai-agents/appointment-coordination',
    path: '/ai-agents/appointment-coordination',
    getParentRoute: () => MarketingRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/privacy-policy': typeof MarketingPrivacyPolicyRoute
  '/terms-of-service': typeof MarketingTermsOfServiceRoute
  '/': typeof MarketingIndexRoute
  '/ai-agents/appointment-coordination': typeof MarketingAiAgentsAppointmentCoordinationRoute
  '/ai-agents/care-coordination': typeof MarketingAiAgentsCareCoordinationRoute
  '/ai-agents/care-gap': typeof MarketingAiAgentsCareGapRoute
  '/ai-agents/chronic-care': typeof MarketingAiAgentsChronicCareRoute
  '/ai-agents/clinical': typeof MarketingAiAgentsClinicalRoute
  '/ai-agents/clinical-documentation': typeof MarketingAiAgentsClinicalDocumentationRoute
  '/ai-agents/coding-billing': typeof MarketingAiAgentsCodingBillingRoute
  '/ai-agents/communication': typeof MarketingAiAgentsCommunicationRoute
  '/ai-agents/denial-management': typeof MarketingAiAgentsDenialManagementRoute
  '/ai-agents/email': typeof MarketingAiAgentsEmailRoute
  '/ai-agents/fax': typeof MarketingAiAgentsFaxRoute
  '/ai-agents/patient-education': typeof MarketingAiAgentsPatientEducationRoute
  '/ai-agents/patient-experience': typeof MarketingAiAgentsPatientExperienceRoute
  '/ai-agents/patient-intake': typeof MarketingAiAgentsPatientIntakeRoute
  '/ai-agents/payment-posting': typeof MarketingAiAgentsPaymentPostingRoute
  '/ai-agents/phone': typeof MarketingAiAgentsPhoneRoute
  '/ai-agents/prior-authorization': typeof MarketingAiAgentsPriorAuthorizationRoute
  '/ai-agents/referral-management': typeof MarketingAiAgentsReferralManagementRoute
  '/ai-agents/revenue-cycle': typeof MarketingAiAgentsRevenueCycleRoute
  '/ai-agents/scribe': typeof MarketingAiAgentsScribeRoute
  '/ai-agents/sms': typeof MarketingAiAgentsSmsRoute
  '/solutions/behavioral-health': typeof MarketingSolutionsBehavioralHealthRoute
  '/solutions/dermatology': typeof MarketingSolutionsDermatologyRoute
  '/solutions/emr-integration': typeof MarketingSolutionsEmrIntegrationRoute
  '/solutions/private-equity': typeof MarketingSolutionsPrivateEquityRoute
  '/solutions/value-based-care': typeof MarketingSolutionsValueBasedCareRoute
  '/ai-agents': typeof MarketingAiAgentsIndexRoute
}
export interface FileRoutesByTo {
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/privacy-policy': typeof MarketingPrivacyPolicyRoute
  '/terms-of-service': typeof MarketingTermsOfServiceRoute
  '/': typeof MarketingIndexRoute
  '/ai-agents/appointment-coordination': typeof MarketingAiAgentsAppointmentCoordinationRoute
  '/ai-agents/care-coordination': typeof MarketingAiAgentsCareCoordinationRoute
  '/ai-agents/care-gap': typeof MarketingAiAgentsCareGapRoute
  '/ai-agents/chronic-care': typeof MarketingAiAgentsChronicCareRoute
  '/ai-agents/clinical': typeof MarketingAiAgentsClinicalRoute
  '/ai-agents/clinical-documentation': typeof MarketingAiAgentsClinicalDocumentationRoute
  '/ai-agents/coding-billing': typeof MarketingAiAgentsCodingBillingRoute
  '/ai-agents/communication': typeof MarketingAiAgentsCommunicationRoute
  '/ai-agents/denial-management': typeof MarketingAiAgentsDenialManagementRoute
  '/ai-agents/email': typeof MarketingAiAgentsEmailRoute
  '/ai-agents/fax': typeof MarketingAiAgentsFaxRoute
  '/ai-agents/patient-education': typeof MarketingAiAgentsPatientEducationRoute
  '/ai-agents/patient-experience': typeof MarketingAiAgentsPatientExperienceRoute
  '/ai-agents/patient-intake': typeof MarketingAiAgentsPatientIntakeRoute
  '/ai-agents/payment-posting': typeof MarketingAiAgentsPaymentPostingRoute
  '/ai-agents/phone': typeof MarketingAiAgentsPhoneRoute
  '/ai-agents/prior-authorization': typeof MarketingAiAgentsPriorAuthorizationRoute
  '/ai-agents/referral-management': typeof MarketingAiAgentsReferralManagementRoute
  '/ai-agents/revenue-cycle': typeof MarketingAiAgentsRevenueCycleRoute
  '/ai-agents/scribe': typeof MarketingAiAgentsScribeRoute
  '/ai-agents/sms': typeof MarketingAiAgentsSmsRoute
  '/solutions/behavioral-health': typeof MarketingSolutionsBehavioralHealthRoute
  '/solutions/dermatology': typeof MarketingSolutionsDermatologyRoute
  '/solutions/emr-integration': typeof MarketingSolutionsEmrIntegrationRoute
  '/solutions/private-equity': typeof MarketingSolutionsPrivateEquityRoute
  '/solutions/value-based-care': typeof MarketingSolutionsValueBasedCareRoute
  '/ai-agents': typeof MarketingAiAgentsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_marketing': typeof MarketingRouteRouteWithChildren
  '/(errors)/401': typeof errors401Route
  '/(errors)/403': typeof errors403Route
  '/(errors)/404': typeof errors404Route
  '/(errors)/500': typeof errors500Route
  '/(errors)/503': typeof errors503Route
  '/_marketing/privacy-policy': typeof MarketingPrivacyPolicyRoute
  '/_marketing/terms-of-service': typeof MarketingTermsOfServiceRoute
  '/_marketing/': typeof MarketingIndexRoute
  '/_marketing/ai-agents/appointment-coordination': typeof MarketingAiAgentsAppointmentCoordinationRoute
  '/_marketing/ai-agents/care-coordination': typeof MarketingAiAgentsCareCoordinationRoute
  '/_marketing/ai-agents/care-gap': typeof MarketingAiAgentsCareGapRoute
  '/_marketing/ai-agents/chronic-care': typeof MarketingAiAgentsChronicCareRoute
  '/_marketing/ai-agents/clinical': typeof MarketingAiAgentsClinicalRoute
  '/_marketing/ai-agents/clinical-documentation': typeof MarketingAiAgentsClinicalDocumentationRoute
  '/_marketing/ai-agents/coding-billing': typeof MarketingAiAgentsCodingBillingRoute
  '/_marketing/ai-agents/communication': typeof MarketingAiAgentsCommunicationRoute
  '/_marketing/ai-agents/denial-management': typeof MarketingAiAgentsDenialManagementRoute
  '/_marketing/ai-agents/email': typeof MarketingAiAgentsEmailRoute
  '/_marketing/ai-agents/fax': typeof MarketingAiAgentsFaxRoute
  '/_marketing/ai-agents/patient-education': typeof MarketingAiAgentsPatientEducationRoute
  '/_marketing/ai-agents/patient-experience': typeof MarketingAiAgentsPatientExperienceRoute
  '/_marketing/ai-agents/patient-intake': typeof MarketingAiAgentsPatientIntakeRoute
  '/_marketing/ai-agents/payment-posting': typeof MarketingAiAgentsPaymentPostingRoute
  '/_marketing/ai-agents/phone': typeof MarketingAiAgentsPhoneRoute
  '/_marketing/ai-agents/prior-authorization': typeof MarketingAiAgentsPriorAuthorizationRoute
  '/_marketing/ai-agents/referral-management': typeof MarketingAiAgentsReferralManagementRoute
  '/_marketing/ai-agents/revenue-cycle': typeof MarketingAiAgentsRevenueCycleRoute
  '/_marketing/ai-agents/scribe': typeof MarketingAiAgentsScribeRoute
  '/_marketing/ai-agents/sms': typeof MarketingAiAgentsSmsRoute
  '/_marketing/solutions/behavioral-health': typeof MarketingSolutionsBehavioralHealthRoute
  '/_marketing/solutions/dermatology': typeof MarketingSolutionsDermatologyRoute
  '/_marketing/solutions/emr-integration': typeof MarketingSolutionsEmrIntegrationRoute
  '/_marketing/solutions/private-equity': typeof MarketingSolutionsPrivateEquityRoute
  '/_marketing/solutions/value-based-care': typeof MarketingSolutionsValueBasedCareRoute
  '/_marketing/ai-agents/': typeof MarketingAiAgentsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/privacy-policy'
    | '/terms-of-service'
    | '/'
    | '/ai-agents/appointment-coordination'
    | '/ai-agents/care-coordination'
    | '/ai-agents/care-gap'
    | '/ai-agents/chronic-care'
    | '/ai-agents/clinical'
    | '/ai-agents/clinical-documentation'
    | '/ai-agents/coding-billing'
    | '/ai-agents/communication'
    | '/ai-agents/denial-management'
    | '/ai-agents/email'
    | '/ai-agents/fax'
    | '/ai-agents/patient-education'
    | '/ai-agents/patient-experience'
    | '/ai-agents/patient-intake'
    | '/ai-agents/payment-posting'
    | '/ai-agents/phone'
    | '/ai-agents/prior-authorization'
    | '/ai-agents/referral-management'
    | '/ai-agents/revenue-cycle'
    | '/ai-agents/scribe'
    | '/ai-agents/sms'
    | '/solutions/behavioral-health'
    | '/solutions/dermatology'
    | '/solutions/emr-integration'
    | '/solutions/private-equity'
    | '/solutions/value-based-care'
    | '/ai-agents'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/privacy-policy'
    | '/terms-of-service'
    | '/'
    | '/ai-agents/appointment-coordination'
    | '/ai-agents/care-coordination'
    | '/ai-agents/care-gap'
    | '/ai-agents/chronic-care'
    | '/ai-agents/clinical'
    | '/ai-agents/clinical-documentation'
    | '/ai-agents/coding-billing'
    | '/ai-agents/communication'
    | '/ai-agents/denial-management'
    | '/ai-agents/email'
    | '/ai-agents/fax'
    | '/ai-agents/patient-education'
    | '/ai-agents/patient-experience'
    | '/ai-agents/patient-intake'
    | '/ai-agents/payment-posting'
    | '/ai-agents/phone'
    | '/ai-agents/prior-authorization'
    | '/ai-agents/referral-management'
    | '/ai-agents/revenue-cycle'
    | '/ai-agents/scribe'
    | '/ai-agents/sms'
    | '/solutions/behavioral-health'
    | '/solutions/dermatology'
    | '/solutions/emr-integration'
    | '/solutions/private-equity'
    | '/solutions/value-based-care'
    | '/ai-agents'
  id:
    | '__root__'
    | '/_marketing'
    | '/(errors)/401'
    | '/(errors)/403'
    | '/(errors)/404'
    | '/(errors)/500'
    | '/(errors)/503'
    | '/_marketing/privacy-policy'
    | '/_marketing/terms-of-service'
    | '/_marketing/'
    | '/_marketing/ai-agents/appointment-coordination'
    | '/_marketing/ai-agents/care-coordination'
    | '/_marketing/ai-agents/care-gap'
    | '/_marketing/ai-agents/chronic-care'
    | '/_marketing/ai-agents/clinical'
    | '/_marketing/ai-agents/clinical-documentation'
    | '/_marketing/ai-agents/coding-billing'
    | '/_marketing/ai-agents/communication'
    | '/_marketing/ai-agents/denial-management'
    | '/_marketing/ai-agents/email'
    | '/_marketing/ai-agents/fax'
    | '/_marketing/ai-agents/patient-education'
    | '/_marketing/ai-agents/patient-experience'
    | '/_marketing/ai-agents/patient-intake'
    | '/_marketing/ai-agents/payment-posting'
    | '/_marketing/ai-agents/phone'
    | '/_marketing/ai-agents/prior-authorization'
    | '/_marketing/ai-agents/referral-management'
    | '/_marketing/ai-agents/revenue-cycle'
    | '/_marketing/ai-agents/scribe'
    | '/_marketing/ai-agents/sms'
    | '/_marketing/solutions/behavioral-health'
    | '/_marketing/solutions/dermatology'
    | '/_marketing/solutions/emr-integration'
    | '/_marketing/solutions/private-equity'
    | '/_marketing/solutions/value-based-care'
    | '/_marketing/ai-agents/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  MarketingRouteRoute: typeof MarketingRouteRouteWithChildren
  errors401Route: typeof errors401Route
  errors403Route: typeof errors403Route
  errors404Route: typeof errors404Route
  errors500Route: typeof errors500Route
  errors503Route: typeof errors503Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_marketing': {
      id: '/_marketing'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof MarketingRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_marketing/': {
      id: '/_marketing/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof MarketingIndexRouteImport
      parentRoute: typeof MarketingRouteRoute
    }
    '/_marketing/terms-of-service': {
      id: '/_marketing/terms-of-service'
      path: '/terms-of-service'
      fullPath: '/terms-of-service'
      preLoaderRoute: typeof MarketingTermsOfServiceRouteImport
      parentRoute: typeof MarketingRouteRoute
    }
    '/_marketing/privacy-policy': {
      id: '/_marketing/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof MarketingPrivacyPolicyRouteImport
      parentRoute: typeof MarketingRouteRoute
    }
    '/(errors)/503': {
      id: '/(errors)/503'
      path: '/503'
      fullPath: '/503'
      preLoaderRoute: typeof errors503RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/500': {
      id: '/(errors)/500'
      path: '/500'
      fullPath: '/500'
      preLoaderRoute: typeof errors500RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/404': {
      id: '/(errors)/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof errors404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/403': {
      id: '/(errors)/403'
      path: '/403'
      fullPath: '/403'
      preLoaderRoute: typeof errors403RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/401': {
      id: '/(errors)/401'
      path: '/401'
      fullPath: '/401'
      preLoaderRoute: typeof errors401RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_marketing/ai-agents/': {
      id: '/_marketing/ai-agents/'
      path: '/ai-agents'
      fullPath: '/ai-agents'
      preLoaderRoute: typeof MarketingAiAgentsIndexRouteImport
      parentRoute: typeof MarketingRouteRoute
    }
    '/_marketing/solutions/value-based-care': {
      id: '/_marketing/solutions/value-based-care'
      path: '/solutions/value-based-care'
      fullPath: '/solutions/value-based-care'
      preLoaderRoute: typeof MarketingSolutionsValueBasedCareRouteImport
      parentRoute: typeof MarketingRouteRoute
    }
    '/_marketing/solutions/private-equity': {
      id: '/_marketing/solutions/private-equity'
      path: '/solutions/private-equity'
      fullPath: '/solutions/private-equity'
      preLoaderRoute: typeof MarketingSolutionsPrivateEquityRouteImport
      parentRoute: typeof MarketingRouteRoute
    }
    '/_marketing/solutions/emr-integration': {
      id: '/_marketing/solutions/emr-integration'
      path: '/solutions/emr-integration'
      fullPath: '/solutions/emr-integration'
      preLoaderRoute: typeof MarketingSolutionsEmrIntegrationRouteImport
      parentRoute: typeof MarketingRouteRoute
    }
    '/_marketing/solutions/dermatology': {
      id: '/_marketing/solutions/dermatology'
      path: '/solutions/dermatology'
      fullPath: '/solutions/dermatology'
      preLoaderRoute: typeof MarketingSolutionsDermatologyRouteImport
      parentRoute: typeof MarketingRouteRoute
    }
    '/_marketing/solutions/behavioral-health': {
      id: '/_marketing/solutions/behavioral-health'
      path: '/solutions/behavioral-health'
      fullPath: '/solutions/behavioral-health'
      preLoaderRoute: typeof MarketingSolutionsBehavioralHealthRouteImport
      parentRoute: typeof MarketingRouteRoute
    }
    '/_marketing/ai-agents/sms': {
      id: '/_marketing/ai-agents/sms'
      path: '/ai-agents/sms'
      fullPath: '/ai-agents/sms'
      preLoaderRoute: typeof MarketingAiAgentsSmsRouteImport
      parentRoute: typeof MarketingRouteRoute
    }
    '/_marketing/ai-agents/scribe': {
      id: '/_marketing/ai-agents/scribe'
      path: '/ai-agents/scribe'
      fullPath: '/ai-agents/scribe'
      preLoaderRoute: typeof MarketingAiAgentsScribeRouteImport
      parentRoute: typeof MarketingRouteRoute
    }
    '/_marketing/ai-agents/revenue-cycle': {
      id: '/_marketing/ai-agents/revenue-cycle'
      path: '/ai-agents/revenue-cycle'
      fullPath: '/ai-agents/revenue-cycle'
      preLoaderRoute: typeof MarketingAiAgentsRevenueCycleRouteImport
      parentRoute: typeof MarketingRouteRoute
    }
    '/_marketing/ai-agents/referral-management': {
      id: '/_marketing/ai-agents/referral-management'
      path: '/ai-agents/referral-management'
      fullPath: '/ai-agents/referral-management'
      preLoaderRoute: typeof MarketingAiAgentsReferralManagementRouteImport
      parentRoute: typeof MarketingRouteRoute
    }
    '/_marketing/ai-agents/prior-authorization': {
      id: '/_marketing/ai-agents/prior-authorization'
      path: '/ai-agents/prior-authorization'
      fullPath: '/ai-agents/prior-authorization'
      preLoaderRoute: typeof MarketingAiAgentsPriorAuthorizationRouteImport
      parentRoute: typeof MarketingRouteRoute
    }
    '/_marketing/ai-agents/phone': {
      id: '/_marketing/ai-agents/phone'
      path: '/ai-agents/phone'
      fullPath: '/ai-agents/phone'
      preLoaderRoute: typeof MarketingAiAgentsPhoneRouteImport
      parentRoute: typeof MarketingRouteRoute
    }
    '/_marketing/ai-agents/payment-posting': {
      id: '/_marketing/ai-agents/payment-posting'
      path: '/ai-agents/payment-posting'
      fullPath: '/ai-agents/payment-posting'
      preLoaderRoute: typeof MarketingAiAgentsPaymentPostingRouteImport
      parentRoute: typeof MarketingRouteRoute
    }
    '/_marketing/ai-agents/patient-intake': {
      id: '/_marketing/ai-agents/patient-intake'
      path: '/ai-agents/patient-intake'
      fullPath: '/ai-agents/patient-intake'
      preLoaderRoute: typeof MarketingAiAgentsPatientIntakeRouteImport
      parentRoute: typeof MarketingRouteRoute
    }
    '/_marketing/ai-agents/patient-experience': {
      id: '/_marketing/ai-agents/patient-experience'
      path: '/ai-agents/patient-experience'
      fullPath: '/ai-agents/patient-experience'
      preLoaderRoute: typeof MarketingAiAgentsPatientExperienceRouteImport
      parentRoute: typeof MarketingRouteRoute
    }
    '/_marketing/ai-agents/patient-education': {
      id: '/_marketing/ai-agents/patient-education'
      path: '/ai-agents/patient-education'
      fullPath: '/ai-agents/patient-education'
      preLoaderRoute: typeof MarketingAiAgentsPatientEducationRouteImport
      parentRoute: typeof MarketingRouteRoute
    }
    '/_marketing/ai-agents/fax': {
      id: '/_marketing/ai-agents/fax'
      path: '/ai-agents/fax'
      fullPath: '/ai-agents/fax'
      preLoaderRoute: typeof MarketingAiAgentsFaxRouteImport
      parentRoute: typeof MarketingRouteRoute
    }
    '/_marketing/ai-agents/email': {
      id: '/_marketing/ai-agents/email'
      path: '/ai-agents/email'
      fullPath: '/ai-agents/email'
      preLoaderRoute: typeof MarketingAiAgentsEmailRouteImport
      parentRoute: typeof MarketingRouteRoute
    }
    '/_marketing/ai-agents/denial-management': {
      id: '/_marketing/ai-agents/denial-management'
      path: '/ai-agents/denial-management'
      fullPath: '/ai-agents/denial-management'
      preLoaderRoute: typeof MarketingAiAgentsDenialManagementRouteImport
      parentRoute: typeof MarketingRouteRoute
    }
    '/_marketing/ai-agents/communication': {
      id: '/_marketing/ai-agents/communication'
      path: '/ai-agents/communication'
      fullPath: '/ai-agents/communication'
      preLoaderRoute: typeof MarketingAiAgentsCommunicationRouteImport
      parentRoute: typeof MarketingRouteRoute
    }
    '/_marketing/ai-agents/coding-billing': {
      id: '/_marketing/ai-agents/coding-billing'
      path: '/ai-agents/coding-billing'
      fullPath: '/ai-agents/coding-billing'
      preLoaderRoute: typeof MarketingAiAgentsCodingBillingRouteImport
      parentRoute: typeof MarketingRouteRoute
    }
    '/_marketing/ai-agents/clinical-documentation': {
      id: '/_marketing/ai-agents/clinical-documentation'
      path: '/ai-agents/clinical-documentation'
      fullPath: '/ai-agents/clinical-documentation'
      preLoaderRoute: typeof MarketingAiAgentsClinicalDocumentationRouteImport
      parentRoute: typeof MarketingRouteRoute
    }
    '/_marketing/ai-agents/clinical': {
      id: '/_marketing/ai-agents/clinical'
      path: '/ai-agents/clinical'
      fullPath: '/ai-agents/clinical'
      preLoaderRoute: typeof MarketingAiAgentsClinicalRouteImport
      parentRoute: typeof MarketingRouteRoute
    }
    '/_marketing/ai-agents/chronic-care': {
      id: '/_marketing/ai-agents/chronic-care'
      path: '/ai-agents/chronic-care'
      fullPath: '/ai-agents/chronic-care'
      preLoaderRoute: typeof MarketingAiAgentsChronicCareRouteImport
      parentRoute: typeof MarketingRouteRoute
    }
    '/_marketing/ai-agents/care-gap': {
      id: '/_marketing/ai-agents/care-gap'
      path: '/ai-agents/care-gap'
      fullPath: '/ai-agents/care-gap'
      preLoaderRoute: typeof MarketingAiAgentsCareGapRouteImport
      parentRoute: typeof MarketingRouteRoute
    }
    '/_marketing/ai-agents/care-coordination': {
      id: '/_marketing/ai-agents/care-coordination'
      path: '/ai-agents/care-coordination'
      fullPath: '/ai-agents/care-coordination'
      preLoaderRoute: typeof MarketingAiAgentsCareCoordinationRouteImport
      parentRoute: typeof MarketingRouteRoute
    }
    '/_marketing/ai-agents/appointment-coordination': {
      id: '/_marketing/ai-agents/appointment-coordination'
      path: '/ai-agents/appointment-coordination'
      fullPath: '/ai-agents/appointment-coordination'
      preLoaderRoute: typeof MarketingAiAgentsAppointmentCoordinationRouteImport
      parentRoute: typeof MarketingRouteRoute
    }
  }
}

interface MarketingRouteRouteChildren {
  MarketingPrivacyPolicyRoute: typeof MarketingPrivacyPolicyRoute
  MarketingTermsOfServiceRoute: typeof MarketingTermsOfServiceRoute
  MarketingIndexRoute: typeof MarketingIndexRoute
  MarketingAiAgentsAppointmentCoordinationRoute: typeof MarketingAiAgentsAppointmentCoordinationRoute
  MarketingAiAgentsCareCoordinationRoute: typeof MarketingAiAgentsCareCoordinationRoute
  MarketingAiAgentsCareGapRoute: typeof MarketingAiAgentsCareGapRoute
  MarketingAiAgentsChronicCareRoute: typeof MarketingAiAgentsChronicCareRoute
  MarketingAiAgentsClinicalRoute: typeof MarketingAiAgentsClinicalRoute
  MarketingAiAgentsClinicalDocumentationRoute: typeof MarketingAiAgentsClinicalDocumentationRoute
  MarketingAiAgentsCodingBillingRoute: typeof MarketingAiAgentsCodingBillingRoute
  MarketingAiAgentsCommunicationRoute: typeof MarketingAiAgentsCommunicationRoute
  MarketingAiAgentsDenialManagementRoute: typeof MarketingAiAgentsDenialManagementRoute
  MarketingAiAgentsEmailRoute: typeof MarketingAiAgentsEmailRoute
  MarketingAiAgentsFaxRoute: typeof MarketingAiAgentsFaxRoute
  MarketingAiAgentsPatientEducationRoute: typeof MarketingAiAgentsPatientEducationRoute
  MarketingAiAgentsPatientExperienceRoute: typeof MarketingAiAgentsPatientExperienceRoute
  MarketingAiAgentsPatientIntakeRoute: typeof MarketingAiAgentsPatientIntakeRoute
  MarketingAiAgentsPaymentPostingRoute: typeof MarketingAiAgentsPaymentPostingRoute
  MarketingAiAgentsPhoneRoute: typeof MarketingAiAgentsPhoneRoute
  MarketingAiAgentsPriorAuthorizationRoute: typeof MarketingAiAgentsPriorAuthorizationRoute
  MarketingAiAgentsReferralManagementRoute: typeof MarketingAiAgentsReferralManagementRoute
  MarketingAiAgentsRevenueCycleRoute: typeof MarketingAiAgentsRevenueCycleRoute
  MarketingAiAgentsScribeRoute: typeof MarketingAiAgentsScribeRoute
  MarketingAiAgentsSmsRoute: typeof MarketingAiAgentsSmsRoute
  MarketingSolutionsBehavioralHealthRoute: typeof MarketingSolutionsBehavioralHealthRoute
  MarketingSolutionsDermatologyRoute: typeof MarketingSolutionsDermatologyRoute
  MarketingSolutionsEmrIntegrationRoute: typeof MarketingSolutionsEmrIntegrationRoute
  MarketingSolutionsPrivateEquityRoute: typeof MarketingSolutionsPrivateEquityRoute
  MarketingSolutionsValueBasedCareRoute: typeof MarketingSolutionsValueBasedCareRoute
  MarketingAiAgentsIndexRoute: typeof MarketingAiAgentsIndexRoute
}

const MarketingRouteRouteChildren: MarketingRouteRouteChildren = {
  MarketingPrivacyPolicyRoute: MarketingPrivacyPolicyRoute,
  MarketingTermsOfServiceRoute: MarketingTermsOfServiceRoute,
  MarketingIndexRoute: MarketingIndexRoute,
  MarketingAiAgentsAppointmentCoordinationRoute:
    MarketingAiAgentsAppointmentCoordinationRoute,
  MarketingAiAgentsCareCoordinationRoute:
    MarketingAiAgentsCareCoordinationRoute,
  MarketingAiAgentsCareGapRoute: MarketingAiAgentsCareGapRoute,
  MarketingAiAgentsChronicCareRoute: MarketingAiAgentsChronicCareRoute,
  MarketingAiAgentsClinicalRoute: MarketingAiAgentsClinicalRoute,
  MarketingAiAgentsClinicalDocumentationRoute:
    MarketingAiAgentsClinicalDocumentationRoute,
  MarketingAiAgentsCodingBillingRoute: MarketingAiAgentsCodingBillingRoute,
  MarketingAiAgentsCommunicationRoute: MarketingAiAgentsCommunicationRoute,
  MarketingAiAgentsDenialManagementRoute:
    MarketingAiAgentsDenialManagementRoute,
  MarketingAiAgentsEmailRoute: MarketingAiAgentsEmailRoute,
  MarketingAiAgentsFaxRoute: MarketingAiAgentsFaxRoute,
  MarketingAiAgentsPatientEducationRoute:
    MarketingAiAgentsPatientEducationRoute,
  MarketingAiAgentsPatientExperienceRoute:
    MarketingAiAgentsPatientExperienceRoute,
  MarketingAiAgentsPatientIntakeRoute: MarketingAiAgentsPatientIntakeRoute,
  MarketingAiAgentsPaymentPostingRoute: MarketingAiAgentsPaymentPostingRoute,
  MarketingAiAgentsPhoneRoute: MarketingAiAgentsPhoneRoute,
  MarketingAiAgentsPriorAuthorizationRoute:
    MarketingAiAgentsPriorAuthorizationRoute,
  MarketingAiAgentsReferralManagementRoute:
    MarketingAiAgentsReferralManagementRoute,
  MarketingAiAgentsRevenueCycleRoute: MarketingAiAgentsRevenueCycleRoute,
  MarketingAiAgentsScribeRoute: MarketingAiAgentsScribeRoute,
  MarketingAiAgentsSmsRoute: MarketingAiAgentsSmsRoute,
  MarketingSolutionsBehavioralHealthRoute:
    MarketingSolutionsBehavioralHealthRoute,
  MarketingSolutionsDermatologyRoute: MarketingSolutionsDermatologyRoute,
  MarketingSolutionsEmrIntegrationRoute: MarketingSolutionsEmrIntegrationRoute,
  MarketingSolutionsPrivateEquityRoute: MarketingSolutionsPrivateEquityRoute,
  MarketingSolutionsValueBasedCareRoute: MarketingSolutionsValueBasedCareRoute,
  MarketingAiAgentsIndexRoute: MarketingAiAgentsIndexRoute,
}

const MarketingRouteRouteWithChildren = MarketingRouteRoute._addFileChildren(
  MarketingRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  MarketingRouteRoute: MarketingRouteRouteWithChildren,
  errors401Route: errors401Route,
  errors403Route: errors403Route,
  errors404Route: errors404Route,
  errors500Route: errors500Route,
  errors503Route: errors503Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
